using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AndanteTribe.Csv.SourceGenerator;

/// <summary>
/// Roslyn incremental source generator that produces <c>ICsvFormatter&lt;T&gt;</c> implementations
/// for every type decorated with <c>[MessagePack.MessagePackObject]</c> in the current compilation,
/// and generates an <c>ICsvFormatterResolver</c> body for every <c>partial class</c> decorated
/// with <c>[AndanteTribe.Csv.GeneratedCsvFormatterResolver]</c>.
/// All generated sources are guarded by <c>#if !DISABLE_CSVTRANSCODER_MESSAGEPACK</c>.
/// </summary>
[Generator]
public sealed class CsvFormatterGenerator : IIncrementalGenerator
{
    private const string MessagePackObjectAttributeFqn = "MessagePack.MessagePackObjectAttribute";
    private const string KeyAttributeFqn = "MessagePack.KeyAttribute";
    private const string IgnoreMemberAttributeFqn = "MessagePack.IgnoreMemberAttribute";
    private const string GeneratedCsvFormatterResolverAttributeFqn = "AndanteTribe.Csv.GeneratedCsvFormatterResolverAttribute";

    // -----------------------------------------------------------------------
    //  Injected attribute source
    // -----------------------------------------------------------------------

    private const string AttributeSource = @"// <auto-generated/>
#nullable enable
#if !DISABLE_CSVTRANSCODER_MESSAGEPACK

namespace AndanteTribe.Csv
{
    /// <summary>
    /// Marks a partial class as the target for the auto-generated
    /// <see cref=""global::AndanteTribe.Csv.ICsvFormatterResolver""/> implementation.
    /// The generator creates formatters for every
    /// <see cref=""MessagePack.MessagePackObjectAttribute""/>-annotated type found in the
    /// current compilation and registers them in the resolver.
    /// Define <c>DISABLE_CSVTRANSCODER_MESSAGEPACK</c> to suppress all generated output.
    /// </summary>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Class,
        Inherited = false,
        AllowMultiple = false)]
    public sealed class GeneratedCsvFormatterResolverAttribute : global::System.Attribute
    {
    }
}

#endif
";

    // -----------------------------------------------------------------------
    //  Models
    // -----------------------------------------------------------------------

    private sealed class TypeModel
    {
        public string FullyQualifiedName { get; set; } = string.Empty;
        public string TypeSimpleName { get; set; } = string.Empty;
        /// <summary>Namespace parts + containing type names used to create nested partial class hierarchy.</summary>
        public List<string> NestingParts { get; set; } = new List<string>();
        /// <summary>Simple formatter class name, e.g. <c>MyTypeCsvFormatter</c>.</summary>
        public string FormatterSimpleName { get; set; } = string.Empty;
        /// <summary>Path to the formatter relative to the resolver class body, e.g. <c>Foo.Bar.MyTypeCsvFormatter</c>.</summary>
        public string FormatterRelativePath { get; set; } = string.Empty;
        public List<KeyMemberModel> Members { get; set; } = new List<KeyMemberModel>();
        public int MaxKey { get; set; }
    }

    private sealed class KeyMemberModel
    {
        public int Key { get; set; }
        public string MemberTypeFqn { get; set; } = string.Empty;
    }

    private sealed class ResolverModel
    {
        public string Namespace { get; set; } = string.Empty;
        public string ClassName { get; set; } = string.Empty;
        public string FileHintName { get; set; } = string.Empty;
        public string Accessibility { get; set; } = "public";
    }

    // -----------------------------------------------------------------------
    //  Initialization
    // -----------------------------------------------------------------------

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Inject [GeneratedCsvFormatterResolver] attribute (guarded by #if !DISABLE_CSVTRANSCODER_MESSAGEPACK).
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource(
                "GeneratedCsvFormatterResolverAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

        // Pipeline 1: collect all [MessagePackObject] types.
        var messagePackTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                MessagePackObjectAttributeFqn,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, ct) => GetTypeModel(ctx, ct))
            .Where(static m => m is not null)
            .Collect();

        // Pipeline 2: collect all [GeneratedCsvFormatterResolver] classes.
        var resolverClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                GeneratedCsvFormatterResolverAttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => GetResolverModel(ctx, ct))
            .Where(static m => m is not null);

        // Output: resolver body file + one file per formatter type.
        // The resolver body carries Instance / GetFormatter / FormatterLookup.
        // Each formatter is a nested partial class inside the resolver, in its own file —
        // the same split-file pattern used by MessagePack-CSharp's source generator.
        context.RegisterSourceOutput(
            resolverClasses.Combine(messagePackTypes),
            static (ctx, pair) =>
            {
                var (resolver, types) = pair;
                if (resolver is null) return;

                var validTypes = types.Where(static t => t is not null).ToList();

                // 1) Resolver body file — Instance, GetFormatter<T>, FormatterLookup.
                ctx.AddSource(
                    resolver.FileHintName + ".g.cs",
                    SourceText.From(GenerateResolverBody(resolver, validTypes), Encoding.UTF8));

                // 2) One partial-class file per formatter type.
                foreach (var type in validTypes)
                {
                    ctx.AddSource(
                        resolver.FileHintName + "." + type!.FormatterSimpleName + ".g.cs",
                        SourceText.From(GenerateFormatterFile(resolver, type), Encoding.UTF8));
                }
            });
    }

    // -----------------------------------------------------------------------
    //  Transform helpers
    // -----------------------------------------------------------------------

    private static TypeModel? GetTypeModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;

        // Skip open generic types — the formatter would also need to be generic, which is unsupported.
        if (typeSymbol.IsGenericType) return null;

        // Skip types that are not publicly or internally accessible (e.g., private nested types).
        // The formatter is always 'internal sealed' but still cannot reference a less-accessible type.
        if (typeSymbol.DeclaredAccessibility != Accessibility.Public &&
            typeSymbol.DeclaredAccessibility != Accessibility.Internal)
            return null;

        var members = new List<KeyMemberModel>();

        foreach (var member in typeSymbol.GetMembers())
        {
            ct.ThrowIfCancellationRequested();

            if (member.IsStatic) continue;
            if (member.DeclaredAccessibility != Accessibility.Public) continue;

            // Skip members marked with [IgnoreMember].
            var hasIgnore = false;
            foreach (var attr in member.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() == IgnoreMemberAttributeFqn)
                {
                    hasIgnore = true;
                    break;
                }
            }

            if (hasIgnore) continue;

            // Resolve the member's type.
            ITypeSymbol? memberType = member switch
            {
                IPropertySymbol prop => prop.Type,
                IFieldSymbol field => field.Type,
                _ => null
            };

            if (memberType is null) continue;

            // Find [Key(int)] attribute (array-mode keys only; string keys are skipped).
            int? keyValue = null;
            foreach (var attr in member.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() != KeyAttributeFqn) continue;
                if (attr.ConstructorArguments.Length > 0
                    && attr.ConstructorArguments[0].Value is int k)
                {
                    keyValue = k;
                    break;
                }
            }

            if (keyValue is null) continue;

            // Skip negative key values — MessagePack's own analyzer already warns about these,
            // and a negative MaxKey would make the array-header loop never run.
            if (keyValue < 0) continue;

            members.Add(new KeyMemberModel
            {
                Key = keyValue.Value,
                MemberTypeFqn = memberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            });
        }

        if (members.Count == 0) return null;

        members.Sort(static (a, b) => a.Key.CompareTo(b.Key));

        var maxKey = members.Max(static m => m.Key);

        var fqn = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Build the nesting parts: namespace segments + containing type names.
        // These are used to create the internal partial class hierarchy inside the resolver.
        var nsParts = typeSymbol.ContainingNamespace is { IsGlobalNamespace: false } nsSymbol
            ? nsSymbol.ToDisplayString().Split('.')
            : System.Array.Empty<string>();

        var containingTypeParts = new List<string>();
        var containingType = typeSymbol.ContainingType;
        while (containingType is not null)
        {
            containingTypeParts.Insert(0, containingType.Name);
            containingType = containingType.ContainingType;
        }

        var nestingParts = new List<string>(nsParts.Length + containingTypeParts.Count);
        nestingParts.AddRange(nsParts);
        nestingParts.AddRange(containingTypeParts);

        var typeSimpleName = typeSymbol.Name;
        var formatterSimpleName = typeSimpleName + "CsvFormatter";
        var formatterRelativePath = nestingParts.Count > 0
            ? string.Join(".", nestingParts) + "." + formatterSimpleName
            : formatterSimpleName;

        return new TypeModel
        {
            FullyQualifiedName = fqn,
            TypeSimpleName = typeSimpleName,
            NestingParts = nestingParts,
            FormatterSimpleName = formatterSimpleName,
            FormatterRelativePath = formatterRelativePath,
            Members = members,
            MaxKey = maxKey
        };
    }

    private static ResolverModel? GetResolverModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return null;

        // Skip generic classes — the generator would emit an incorrect (non-generic) partial
        // declaration that clashes with the user's generic type.
        if (classSymbol.IsGenericType) return null;

        var ns = classSymbol.ContainingNamespace is { IsGlobalNamespace: false } nsSymbol
            ? nsSymbol.ToDisplayString()
            : string.Empty;

        var className = classSymbol.Name;
        // Use dot-separated PascalCase for the hint name (e.g. "MyNs.MyResolver").
        var fileHintName = ns.Length > 0 ? ns + "." + className : className;

        var accessibilityKeyword = classSymbol.DeclaredAccessibility == Accessibility.Internal
            ? "internal"
            : "public";

        return new ResolverModel
        {
            Namespace = ns,
            ClassName = className,
            FileHintName = fileHintName,
            Accessibility = accessibilityKeyword
        };
    }

    // -----------------------------------------------------------------------
    //  Code generation
    // -----------------------------------------------------------------------

    /// <summary>
    /// Generates the resolver body partial class (Instance, GetFormatter, FormatterLookup).
    /// Formatter classes are emitted in separate files via <see cref="GenerateFormatterFile"/>.
    /// </summary>
    private static string GenerateResolverBody(ResolverModel model, List<TypeModel?> validTypes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#if !DISABLE_CSVTRANSCODER_MESSAGEPACK");
        sb.AppendLine();

        var outerIndent = string.Empty;
        if (model.Namespace.Length > 0)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
            outerIndent = "    ";
        }

        var bodyIndent = outerIndent + "    ";

        sb.AppendLine($"{outerIndent}{model.Accessibility} partial class {model.ClassName} : global::AndanteTribe.Csv.ICsvFormatterResolver");
        sb.AppendLine($"{outerIndent}{{");
        sb.AppendLine($"{bodyIndent}public static readonly {model.ClassName} Instance = new {model.ClassName}();");
        sb.AppendLine();
        sb.AppendLine($"{bodyIndent}private {model.ClassName}() {{ }}");
        sb.AppendLine();
        sb.AppendLine($"{bodyIndent}private static class Cache<T>");
        sb.AppendLine($"{bodyIndent}{{");
        sb.AppendLine($"{bodyIndent}    public static readonly global::AndanteTribe.Csv.ICsvFormatter<T>? Value =");
        sb.AppendLine($"{bodyIndent}        FormatterLookup.GetFormatter(typeof(T)) as global::AndanteTribe.Csv.ICsvFormatter<T>;");
        sb.AppendLine($"{bodyIndent}}}");
        sb.AppendLine();
        sb.AppendLine($"{bodyIndent}public global::AndanteTribe.Csv.ICsvFormatter<T>? GetFormatter<T>() => Cache<T>.Value;");
        sb.AppendLine();

        // Private FormatterLookup class — no global namespace needed; each resolver has its own.
        sb.AppendLine($"{bodyIndent}private static class FormatterLookup");
        sb.AppendLine($"{bodyIndent}{{");
        sb.AppendLine($"{bodyIndent}    public static object? GetFormatter(global::System.Type t)");
        sb.AppendLine($"{bodyIndent}    {{");

        foreach (var type in validTypes)
        {
            sb.AppendLine($"{bodyIndent}        if (t == typeof({type!.FullyQualifiedName}))");
            sb.AppendLine($"{bodyIndent}            return {type.FormatterRelativePath}.Instance;");
        }

        sb.AppendLine($"{bodyIndent}        return null;");
        sb.AppendLine($"{bodyIndent}    }}");
        sb.AppendLine($"{bodyIndent}}}");

        sb.AppendLine($"{outerIndent}}}");

        if (model.Namespace.Length > 0)
            sb.AppendLine("}");

        sb.AppendLine();
        sb.Append("#endif");

        return sb.ToString();
    }

    /// <summary>
    /// Generates a partial-class file that contains exactly one formatter class nested inside
    /// the resolver class. The type's namespace is mirrored as <c>internal partial class</c>
    /// wrappers, following the same pattern as MessagePack-CSharp's source generator.
    /// </summary>
    private static string GenerateFormatterFile(ResolverModel resolver, TypeModel type)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#if !DISABLE_CSVTRANSCODER_MESSAGEPACK");
        sb.AppendLine();

        var outerIndent = string.Empty;
        if (resolver.Namespace.Length > 0)
        {
            sb.AppendLine($"namespace {resolver.Namespace}");
            sb.AppendLine("{");
            outerIndent = "    ";
        }

        var bodyIndent = outerIndent + "    ";

        sb.AppendLine($"{outerIndent}{resolver.Accessibility} partial class {resolver.ClassName}");
        sb.AppendLine($"{outerIndent}{{");

        AppendFormatterBlock(sb, type, bodyIndent);

        sb.AppendLine($"{outerIndent}}}");

        if (resolver.Namespace.Length > 0)
            sb.AppendLine("}");

        sb.AppendLine();
        sb.Append("#endif");

        return sb.ToString();
    }

    /// <summary>
    /// Appends the formatter class for <paramref name="model"/> inside the resolver class body,
    /// wrapping it in <c>internal partial class</c> declarations that mirror the type's namespace
    /// and containing-type hierarchy.
    /// </summary>
    private static void AppendFormatterBlock(StringBuilder sb, TypeModel model, string baseIndent)
    {
        // Pre-compute indents for each nesting level.
        var indents = new string[model.NestingParts.Count + 1];
        for (var i = 0; i <= model.NestingParts.Count; i++)
            indents[i] = baseIndent + new string(' ', i * 4);

        // Open nested partial class wrappers (one per namespace segment / containing type).
        for (var i = 0; i < model.NestingParts.Count; i++)
        {
            sb.AppendLine($"{indents[i]}internal partial class {model.NestingParts[i]}");
            sb.AppendLine($"{indents[i]}{{");
        }

        var fi = indents[model.NestingParts.Count]; // formatter class indent

        sb.AppendLine($"{fi}/// <summary>Auto-generated <c>ICsvFormatter</c> for <see cref=\"{model.FullyQualifiedName}\"/>.</summary>");
        sb.AppendLine($"{fi}internal sealed class {model.FormatterSimpleName} : global::AndanteTribe.Csv.ICsvFormatter<{model.FullyQualifiedName}>");
        sb.AppendLine($"{fi}{{");
        sb.AppendLine($"{fi}    public static readonly {model.FormatterSimpleName} Instance = new {model.FormatterSimpleName}();");
        sb.AppendLine();
        sb.AppendLine($"{fi}    private {model.FormatterSimpleName}() {{ }}");
        sb.AppendLine();
        sb.AppendLine($"{fi}    public void Transcode(ref global::MessagePack.MessagePackWriter writer, ref global::AndanteTribe.Csv.CsvReader reader)");
        sb.AppendLine($"{fi}    {{");
        sb.AppendLine($"{fi}        writer.WriteArrayHeader({model.MaxKey + 1});");

        // Build O(1) key lookup; ContainsKey ensures first declaration wins for duplicate keys.
        var membersByKey = new Dictionary<int, KeyMemberModel>();
        foreach (var m in model.Members)
        {
            if (!membersByKey.ContainsKey(m.Key))
                membersByKey[m.Key] = m;
        }

        for (var key = 0; key <= model.MaxKey; key++)
        {
            if (membersByKey.TryGetValue(key, out var member))
            {
                sb.AppendLine(
                    $"{fi}        global::AndanteTribe.Csv.FormatterResolverExtensions.GetFormatterWithVerify<{member.MemberTypeFqn}>(reader.Options.Resolver).Transcode(ref writer, ref reader);");
            }
            else
            {
                // Sparse key: write nil without consuming a CSV field.
                sb.AppendLine($"{fi}        writer.WriteNil();");
            }
        }

        sb.AppendLine($"{fi}    }}");
        sb.AppendLine($"{fi}}}");

        // Close nested partial class wrappers (innermost first).
        for (var i = model.NestingParts.Count - 1; i >= 0; i--)
            sb.AppendLine($"{indents[i]}}}");
    }
}
