using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AndanteTribe.Csv.SourceGenerator;

/// <summary>
/// Roslyn incremental source generator that produces <c>ICsvFormatter&lt;T&gt;</c> implementations
/// for every type decorated with <c>[MessagePack.MessagePackObject]</c> in the current compilation,
/// and generates an <c>ICsvFormatterResolver</c> body for every <c>partial class</c> decorated
/// with <c>[GeneratedCsvFormatterResolver]</c>.
/// </summary>
[Generator]
public sealed class CsvFormatterGenerator : IIncrementalGenerator
{
    private const string MessagePackObjectAttributeFqn = "MessagePack.MessagePackObjectAttribute";
    private const string KeyAttributeFqn = "MessagePack.KeyAttribute";
    private const string IgnoreMemberAttributeFqn = "MessagePack.IgnoreMemberAttribute";
    private const string GeneratedCsvFormatterResolverAttributeFqn = "AndanteTribe.Csv.GeneratedCsvFormatterResolverAttribute";

    // -----------------------------------------------------------------------
    //  Injected attribute source
    // -----------------------------------------------------------------------

    private const string AttributeSource = @"// <auto-generated/>
#nullable enable

namespace AndanteTribe.Csv
{
    /// <summary>
    /// Marks a partial class as the target for the auto-generated
    /// <see cref=""global::AndanteTribe.Csv.ICsvFormatterResolver""/> implementation.
    /// The generator creates formatters for every
    /// <see cref=""MessagePack.MessagePackObjectAttribute""/>-annotated type found in the
    /// current compilation and registers them in the resolver.
    /// </summary>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Class,
        Inherited = false,
        AllowMultiple = false)]
    internal sealed class GeneratedCsvFormatterResolverAttribute : global::System.Attribute
    {
    }
}
";

    // -----------------------------------------------------------------------
    //  Models
    // -----------------------------------------------------------------------

    private sealed class TypeModel
    {
        public string FullyQualifiedName { get; set; } = string.Empty;
        public string FormatterClassName { get; set; } = string.Empty;
        public string FileHintName { get; set; } = string.Empty;
        public List<KeyMemberModel> Members { get; set; } = new List<KeyMemberModel>();
        public int MaxKey { get; set; }
    }

    private sealed class KeyMemberModel
    {
        public int Key { get; set; }
        public string MemberTypeFqn { get; set; } = string.Empty;
    }

    private sealed class ResolverModel
    {
        public string Namespace { get; set; } = string.Empty;
        public string ClassName { get; set; } = string.Empty;
        public string FileHintName { get; set; } = string.Empty;
    }

    // -----------------------------------------------------------------------
    //  Initialization
    // -----------------------------------------------------------------------

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Inject [GeneratedCsvFormatterResolver] attribute into the compilation.
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource(
                "GeneratedCsvFormatterResolverAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

        // Pipeline 1: collect all [MessagePackObject] types.
        var messagePackTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                MessagePackObjectAttributeFqn,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, ct) => GetTypeModel(ctx, ct))
            .Where(static m => m is not null)
            .Collect();

        // Pipeline 2: collect all [GeneratedCsvFormatterResolver] classes.
        var resolverClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                GeneratedCsvFormatterResolverAttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => GetResolverModel(ctx, ct))
            .Where(static m => m is not null);

        // Output: one formatter file per [MessagePackObject] type.
        context.RegisterSourceOutput(messagePackTypes, static (ctx, types) =>
        {
            foreach (var type in types)
            {
                if (type is null) continue;
                ctx.AddSource(
                    type.FileHintName + ".g.cs",
                    SourceText.From(GenerateFormatter(type), Encoding.UTF8));
            }
        });

        // Output: one resolver file per [GeneratedCsvFormatterResolver] class.
        context.RegisterSourceOutput(
            resolverClasses.Combine(messagePackTypes),
            static (ctx, pair) =>
            {
                var (resolver, types) = pair;
                if (resolver is null) return;
                ctx.AddSource(
                    resolver.FileHintName + ".g.cs",
                    SourceText.From(GenerateResolver(resolver, types), Encoding.UTF8));
            });
    }

    // -----------------------------------------------------------------------
    //  Transform helpers
    // -----------------------------------------------------------------------

    private static TypeModel? GetTypeModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;

        // Skip open generic types — the formatter would also need to be generic, which is unsupported.
        if (typeSymbol.IsGenericType) return null;

        var members = new List<KeyMemberModel>();

        foreach (var member in typeSymbol.GetMembers())
        {
            ct.ThrowIfCancellationRequested();

            if (member.IsStatic) continue;
            if (member.DeclaredAccessibility != Accessibility.Public) continue;

            // Skip members marked with [IgnoreMember].
            var hasIgnore = false;
            foreach (var attr in member.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() == "MessagePack.IgnoreMemberAttribute")
                {
                    hasIgnore = true;
                    break;
                }
            }

            if (hasIgnore) continue;

            // Resolve the member's type.
            ITypeSymbol? memberType = member switch
            {
                IPropertySymbol prop => prop.Type,
                IFieldSymbol field => field.Type,
                _ => null
            };

            if (memberType is null) continue;

            // Find [Key(int)] attribute (array-mode keys only; string keys are skipped).
            int? keyValue = null;
            foreach (var attr in member.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() != "MessagePack.KeyAttribute") continue;
                if (attr.ConstructorArguments.Length > 0
                    && attr.ConstructorArguments[0].Value is int k)
                {
                    keyValue = k;
                    break;
                }
            }

            if (keyValue is null) continue;

            members.Add(new KeyMemberModel
            {
                Key = keyValue.Value,
                MemberTypeFqn = memberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            });
        }

        if (members.Count == 0) return null;

        members.Sort(static (a, b) => a.Key.CompareTo(b.Key));

        var maxKey = members.Max(static m => m.Key);

        var fqn = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Build a unique, file-system-safe class name based on the full type name.
        var flatName = typeSymbol
            .ToDisplayString()
            .Replace(".", "_")
            .Replace("<", "_")
            .Replace(">", string.Empty)
            .Replace(",", "_")
            .Replace(" ", string.Empty);

        return new TypeModel
        {
            FullyQualifiedName = fqn,
            FormatterClassName = flatName + "CsvFormatter",
            FileHintName = "Formatter_" + flatName,
            Members = members,
            MaxKey = maxKey
        };
    }

    private static ResolverModel? GetResolverModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return null;

        var ns = classSymbol.ContainingNamespace is { IsGlobalNamespace: false } nsSymbol
            ? nsSymbol.ToDisplayString()
            : string.Empty;

        var className = classSymbol.Name;
        var fileHintName = "Resolver_"
            + (ns.Length > 0 ? ns.Replace(".", "_") + "_" : string.Empty)
            + className;

        return new ResolverModel
        {
            Namespace = ns,
            ClassName = className,
            FileHintName = fileHintName
        };
    }

    // -----------------------------------------------------------------------
    //  Code generation
    // -----------------------------------------------------------------------

    private static string GenerateFormatter(TypeModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace AndanteTribe.Csv.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Auto-generated <c>ICsvFormatter</c> for <see cref=\"{model.FullyQualifiedName}\"/>.</summary>");
        sb.AppendLine($"    public sealed class {model.FormatterClassName} : global::AndanteTribe.Csv.ICsvFormatter<{model.FullyQualifiedName}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static readonly {model.FormatterClassName} Instance = new {model.FormatterClassName}();");
        sb.AppendLine();
        sb.AppendLine($"        private {model.FormatterClassName}() {{ }}");
        sb.AppendLine();
        sb.AppendLine("        public void Transcode(ref global::MessagePack.MessagePackWriter writer, ref global::AndanteTribe.Csv.CsvReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine($"            writer.WriteArrayHeader({model.MaxKey + 1});");

        // Build index for O(1) lookup while iterating over 0..maxKey.
        var membersByKey = new Dictionary<int, KeyMemberModel>();
        foreach (var m in model.Members)
            membersByKey[m.Key] = m;

        for (var key = 0; key <= model.MaxKey; key++)
        {
            if (membersByKey.TryGetValue(key, out var member))
            {
                sb.AppendLine(
                    $"            global::AndanteTribe.Csv.FormatterResolverExtensions.GetFormatterWithVerify<{member.MemberTypeFqn}>(reader.Options.Resolver).Transcode(ref writer, ref reader);");
            }
            else
            {
                // Sparse key: write nil without consuming a CSV field.
                sb.AppendLine("            writer.WriteNil();");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.Append("}");

        return sb.ToString();
    }

    private static string GenerateResolver(ResolverModel model, ImmutableArray<TypeModel?> types)
    {
        var validTypes = types.Where(static t => t is not null).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var indent = string.Empty;
        if (model.Namespace.Length > 0)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        sb.AppendLine($"{indent}partial class {model.ClassName} : global::AndanteTribe.Csv.ICsvFormatterResolver");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    public static readonly {model.ClassName} Instance = new {model.ClassName}();");
        sb.AppendLine();
        sb.AppendLine($"{indent}    private {model.ClassName}() {{ }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    private static class Cache<T>");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        public static readonly global::AndanteTribe.Csv.ICsvFormatter<T>? Value =");
        sb.AppendLine($"{indent}            global::AndanteTribe.Csv.Generated.{model.ClassName}FormatterLookup.GetFormatter(typeof(T)) as global::AndanteTribe.Csv.ICsvFormatter<T>;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    public global::AndanteTribe.Csv.ICsvFormatter<T>? GetFormatter<T>() => Cache<T>.Value;");
        sb.AppendLine($"{indent}}}");

        if (model.Namespace.Length > 0)
            sb.AppendLine("}");

        // Companion lookup class in the Generated namespace.
        sb.AppendLine();
        sb.AppendLine("namespace AndanteTribe.Csv.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    internal static class {model.ClassName}FormatterLookup");
        sb.AppendLine("    {");
        sb.AppendLine("        public static object? GetFormatter(global::System.Type t)");
        sb.AppendLine("        {");

        foreach (var type in validTypes)
        {
            sb.AppendLine($"            if (t == typeof({type!.FullyQualifiedName}))");
            sb.AppendLine($"                return global::AndanteTribe.Csv.Generated.{type.FormatterClassName}.Instance;");
        }

        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.Append("}");

        return sb.ToString();
    }
}
