name: dotnet-test
on:
    pull_request:
        types:
            - opened
            - synchronize
        paths:
            - 'src/**'
            - 'tests/**'
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - 'tests/**'
    workflow_dispatch: {}
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: windows-latest
        permissions:
            contents: read
        strategy:
            matrix:
                include:
                    - dotnet-version: '10.0.x'
                      framework: 'net10.0'
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: ${{ matrix.dotnet-version }}
            - run: dotnet restore ./tests/CsvTranscoder.MessagePack.Tests
            - run: dotnet restore ./tests/CsvTranscoder.MessagePack.SourceGenerator.Tests
            - run: dotnet build ./tests/CsvTranscoder.MessagePack.Tests --configuration Release --no-restore
            - run: dotnet build ./tests/CsvTranscoder.MessagePack.SourceGenerator.Tests --configuration Release --no-restore
            - run: dotnet test ./tests/CsvTranscoder.MessagePack.Tests --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --framework ${{ matrix.framework }}
            - run: dotnet test ./tests/CsvTranscoder.MessagePack.SourceGenerator.Tests --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --framework ${{ matrix.framework }}
            - name: Run ReportGenerator
              if: matrix.framework == 'net10.0'
              shell: pwsh
              run: |
                  dotnet tool install -g dotnet-reportgenerator-globaltool
                  reportgenerator "-reports:**\coverage.cobertura.xml" -targetdir:"report" -reporttypes:"Html;MarkdownSummary"
                  Get-Content report/Summary.md | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Encoding utf8
            - uses: actions/upload-artifact@v4
              if: matrix.framework == 'net10.0'
              with:
                  name: coverage-report-${{ matrix.framework }}
                  path: report/
